baseURL = 'https://superusers_archive.github.io/'
languageCode = 'en-us'
title = "superuser archive"

paginate = 5

[params]
 description = "supueruser hash's"
 dateFormat = "Jan 2, 20024"

[taxonomies]
 category = "categories"
 author ="authors"